version: '3.8'

services:
  user-service:
    image: user-service:0.0.1
    container_name: user-service-app
    env_file:
      - .env
    ports:
      - "80:8080"
    networks:
      - user-network
    volumes:
      - ./logs:/user-service/logs
      - ./data:/user-service/data

networks:
  user-network:
    driver: bridge
