version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sample_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
