spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user-service
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true