spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user-service
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: email,profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google